---
title: "Assignment 1"
output: html_document
---

This is assignment 1 for ECE579 (w2019). This is my first significant project with the following technologies:

- R Notebooks
- GitHub Pages
- Plotly

If you are a student, please be sure to read the [Univerisity of Michigan Code of Conduct](http://catalog.umd.umich.edu/undergraduate/academic-policies/academic-code-conduct/).

## Links
Here are the important links:

- Website: [https://cooperstansbury.github.io/EDA_r_ece579/index.html](https://cooperstansbury.github.io/EDA_r_ece579/index.html)
- GitHub repository: [https://github.com/CooperStansbury/EDA_r_ece579](https://github.com/CooperStansbury/EDA_r_ece579)
- Car Seats Analysis: [https://raw.githubusercontent.com/CooperStansbury/EDA_r_ece579/master/carseats.Rmd](https://raw.githubusercontent.com/CooperStansbury/EDA_r_ece579/master/carseats.Rmd)
- Western Collaborative Group Study Analysis: [https://raw.githubusercontent.com/CooperStansbury/EDA_r_ece579/master/wcgs.Rmd](https://raw.githubusercontent.com/CooperStansbury/EDA_r_ece579/master/wcgs.Rmd)

## Overview

"The overall objective of this assignment is to develop the core techniques that can be used to examine a basic data set, including scatter plots, and basic linear and logistic regression."

## Citations

1. “Tutorial on 5 Powerful R Packages used for imputing missing values,” Analytics Vidhya, 04-Mar-2016. .

1. M. Clark, A workshop on latent variables models including factor analysis, PCA, SEM, etc.: m-clark/latent-variable-models-workshop-2019. 2019.

1. “Creating websites in R.” [Online]. Available: https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html. [Accessed: 07-Mar-2019].

1. “GitHub and RStudio | GitHub Resources.” [Online]. Available: https://resources.github.com/whitepapers/github-and-rstudio/. [Accessed: 07-Mar-2019].

1. “Markdown Basics.” [Online]. Available: https://rmarkdown.rstudio.com/authoring_basics.html. [Accessed: 07-Mar-2019].

1. “plotly.” [Online]. Available: https://plot.ly/r/. [Accessed: 07-Mar-2019].

1. “Plotting your logistic regression models | R Club.” [Online]. Available: https://blogs.uoregon.edu/rclub/2016/04/05/plotting-your-logistic-regression-models/. [Accessed: 07-Mar-2019].

